---
- name: Add vpn users to RouterOS
  hosts: mikrotik
  gather_facts: false
  vars_prompt:

    - name: ansible_user
      prompt: "RouterOS: Enter the username"
      private: false

    - name: ansible_ssh_pass
      prompt: "RouterOS: Enter the password"
      private: false
        
  tasks:

  - name: Import secrets from vault
    ansible.builtin.include_vars:
      file: "vault.yaml"

  - name: Add users
    community.routeros.command:
      commands:
        - /ppp secret add name="{{ item.name }}" password="{{ item.password }}" profile="{{ profile }}"
    with_items: "{{ user_details }}"